### ISSUE TITLE
Opposite params

### ISSUE THREAD

**Issue by renannery** [39ro/firestore-admin-utils#3]
I'm trying to reference a collection but it seems to me that CollectionHelper is actually taking a DocumentReference.

https://github.com/39ro/admin-utils-firestore/blob/247b7c62b5f86d9b35cf90bfa0d42fd610c1592e/src/helpers.ts#L141-L142

**Comment by 39ro** [comment]
Hi @renannery and thanks for reporting this issue. Version 0.1.6 include this fix.
